### ISSUE TITLE
failed in running generate_licenses.py

### ISSUE THREAD

**Issue by qing-wang** [crow-misia/libwebrtc-bin#17]
while running generate_licenses.py, got the exception stacktrace as followings:

python3 /Users/user/work/GitHub/libwebrtc-bin/webrtc/src/tools_webrtc/libs/generate_licenses.py --target :webrtc /Users/user/work/GitHub/libwebrtc-bin/webrtc_build /Users/user/work/GitHub/libwebrtc-bin/webrtc_build
Traceback (most recent call last):
  File "/Users/user/work/GitHub/libwebrtc-bin/webrtc/src/tools_webrtc/libs/generate_licenses.py", line 272, in <module>
    sys.exit(main())
  File "/Users/user/work/GitHub/libwebrtc-bin/webrtc/src/tools_webrtc/libs/generate_licenses.py", line 268, in main
    builder.GenerateLicenseText(args.output_dir)
  File "/Users/user/work/GitHub/libwebrtc-bin/webrtc/src/tools_webrtc/libs/generate_licenses.py", line 211, in GenerateLicenseText
    third_party_libs |= self._GetThirdPartyLibraries(buildfile, target)
  File "/Users/user/work/GitHub/libwebrtc-bin/webrtc/src/tools_webrtc/libs/generate_licenses.py", line 197, in _GetThirdPartyLibraries
    output = json.loads(LicenseBuilder._RunGN(buildfile_dir, target))
  File "/Applications/Xcode.app/Contents/Developer/Library/Frameworks/Python3.framework/Versions/3.8/lib/python3.8/json/__init__.py", line 357, in loads
    return _default_decoder.decode(s)
  File "/Applications/Xcode.app/Contents/Developer/Library/Frameworks/Python3.framework/Versions/3.8/lib/python3.8/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/Applications/Xcode.app/Contents/Developer/Library/Frameworks/Python3.framework/Versions/3.8/lib/python3.8/json/decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

**Comment by crow-misia** [comment]
@qing-wang 
What commit hash and what build is being executed?
I cannot help you because I am not author of generate_licenses.py.
In my experience, it often happens because of incorrect parameters in gn command.

**Comment by qing-wang** [comment]
sorry, this is caused by my bad.

I made a wrong setting in args.gn. After printing some logs, I finally figured out the problem. There is no problem now.
