### ISSUE TITLE
FAILED: obj/third_party/ffmpeg/ffmpeg_internal/autorename_libavutil_arm_cpu.o

### ISSUE THREAD

**Issue by netstalkerr** [crow-misia/libwebrtc-bin#29]
Thanks for sharing this tool.
I have an exception when trying to build webrtc for android with H264:

branch:
`m109`

my env: 
```
USE_CCACHE ?= 1
USE_H264 ?= 1
USE_X11 ?= 1
```

my command:
`~/libwebrtc-bin$ sudo make -C docker android`

after some time:
`[3454/4383] CC obj/third_party/ffmpeg/ffmpeg_internal/vorbisdsp_init_arm.o
[3455/4383] CC obj/third_party/ffmpeg/ffmpeg_internal/rdft_init_arm.o
[3456/4383] CC obj/third_party/ffmpeg/ffmpeg_internal/autorename_libavutil_arm_cpu.o
FAILED: obj/third_party/ffmpeg/ffmpeg_internal/autorename_libavutil_arm_cpu.o 
/root/webrtc/third_party/ccache ../../../webrtc/src/third_party/llvm-build/Release+Asserts/bin/clang -MMD -MF obj/third_party/ffmpeg/ffmpeg_internal/autorename_libavutil_arm_cpu.o.d -DHAVE_AV_CONFIG_H -D_POSIX_C_SOURCE=200112 -D_XOPEN_SOURCE=600 -DPIC -DFFMPEG_CONFIGURATION=NULL -D_ISOC99_SOURCE -D_LARGEFILE_SOURCE -D_GNU_SOURCE -DANDROID -DHAVE_SYS_UIO_H -DANDROID_NDK_VERSION_ROLL=r23_1 -DCR_CLANG_REVISION=\"llvmorg-16-init-9369-g87a20868-1\" -D_LIBCPP_DISABLE_VISIBILITY_ANNOTATIONS -D_LIBCXXABI_DISABLE_VISIBILITY_ANNOTATIONS -DCR_LIBCXX_REVISION=fc6bbc5eb039769b5ed2de84444a3c6f9b45a598 -D_LIBCPP_ENABLE_ASSERTIONS_DEFAULT=1 -D_LIBCPP_AVAILABILITY_CUSTOM_VERBOSE_ABORT_PROVIDED=1 -DNDEBUG -DNVALGRIND -DDYNAMIC_ANNOTATIONS_ENABLED=0 -DOPUS_FIXED_POINT -I../../../webrtc/src/third_party/ffmpeg/chromium/config/Chromium/android/arm-neon -I../../../webrtc/src/third_party/ffmpeg -I../../../webrtc/src -Igen -I../../../webrtc/src/buildtools/third_party/libc++ -I../../../webrtc/src/third_party/opus/src/include -fPIC -Wno-deprecated-declarations -fomit-frame-pointer -std=c99 -pthread -fno-math-errno -fno-signed-zeros -fno-tree-vectorize -fno-delete-null-pointer-checks -fno-ident -fno-strict-aliasing --param=ssp-buffer-size=4 -fstack-protector -funwind-tables -fPIC -fcolor-diagnostics -fmerge-all-constants -fcrash-diagnostics-dir=../../../webrtc/src/tools/clang/crashreports -mllvm -instcombine-lower-dbg-declare=0 -ffp-contract=off -fcomplete-member-pointers -ffunction-sections -fno-short-enums --target=arm-linux-androideabi16 -march=armv7-a -mfloat-abi=softfp -Wno-builtin-macro-redefined -D__DATE__= -D__TIME__= -D__TIMESTAMP__= -ffile-compilation-dir=. -no-canonical-prefixes -mfpu=neon -mthumb -gdwarf-4 -g1 -gdwarf-aranges -fdebug-info-for-profiling -fvisibility=hidden -Xclang -add-plugin -Xclang find-bad-constructs -Xclang -plugin-arg-find-bad-constructs -Xclang raw-ref-template-as-trivial-member -Xclang -plugin-arg-find-bad-constructs -Xclang check-ipc -Wheader-hygiene -Wstring-conversion -Wtautological-overlap-compare -Werror -Wall -Wno-unused-variable -Wno-c++11-narrowing -Wno-unused-but-set-variable -Wno-misleading-indentation -Wno-missing-field-initializers -Wno-unused-parameter -Wno-psabi -Wloop-analysis -Wno-unneeded-internal-declaration -Wenum-compare-conditional -Wno-ignored-pragma-optimize -Wno-deprecated-builtins -Wno-bitfield-constant-conversion -Wno-incompatible-pointer-types -Wno-absolute-value -Wno-deprecated-declarations -Wno-incompatible-pointer-types -Wno-logical-op-parentheses -Wno-parentheses -Wno-pointer-sign -Wno-switch -Wno-unused-label -Wno-unused-variable -Wno-string-conversion -Wno-sometimes-uninitialized -Wno-unguarded-availability -Wno-unused-function -Wno-constant-conversion -Wno-string-plus-int -Wno-tautological-constant-out-of-range-compare -Wno-implicit-int-float-conversion -Wno-inline-asm -O2 -fdata-sections -ffunction-sections -fno-unique-section-names -std=c11 --sysroot=../../../webrtc/src/third_party/android_ndk/toolchains/llvm/prebuilt/linux-x86_64/sysroot -c ../../../webrtc/src/third_party/ffmpeg/libavutil/arm/autorename_libavutil_arm_cpu.c -o obj/third_party/ffmpeg/ffmpeg_internal/autorename_libavutil_arm_cpu.o
In file included from ../../../webrtc/src/third_party/ffmpeg/libavutil/arm/autorename_libavutil_arm_cpu.c:2:
../../../webrtc/src/third_party/ffmpeg/libavutil/arm/cpu.c:58:25: error: call to undeclared function 'getauxval'; ISO C99 and later do not support implicit function declarations [-Wimplicit-function-declaration]
    unsigned long ret = getauxval(AT_HWCAP);
                        ^
../../../webrtc/src/third_party/ffmpeg/libavutil/arm/cpu.c:58:25: note: did you mean 'get_auxval'?
../../../webrtc/src/third_party/ffmpeg/libavutil/arm/cpu.c:55:12: note: 'get_auxval' declared here
static int get_auxval(uint32_t *hwcap)
           ^
1 error generated.
[3457/4383] CC obj/third_party/ffmpeg/ffmpeg_internal/float_dsp_init_arm.o
[3458/4383] CC obj/third_party/ffmpeg/ffmpeg_internal/float_dsp_init_vfp.o
[3459/4383] CC obj/third_party/ffmpeg/ffmpeg_internal/float_dsp_init_neon.o
[3460/4383] CC obj/third_party/ffmpeg/ffmpeg_internal/tx_double.o
[3461/4383] CC obj/third_party/ffmpeg/ffmpeg_internal/tx_int32.o
ninja: build stopped: subcommand failed.
Traceback (most recent call last):
  File "/root/webrtc/src/tools_webrtc/android/build_aar.py", line 269, in <module>
    sys.exit(main())
  File "/root/webrtc/src/tools_webrtc/android/build_aar.py", line 263, in main
    BuildAar(args.arch, args.output, args.use_goma, args.use_remoteexec,
  File "/root/webrtc/src/tools_webrtc/android/build_aar.py", line 243, in BuildAar
    Build(build_dir, arch, use_goma, use_remoteexec, extra_gn_args,
  File "/root/webrtc/src/tools_webrtc/android/build_aar.py", line 198, in Build
    _RunNinja(output_directory, ninja_args)
  File "/root/webrtc/src/tools_webrtc/android/build_aar.py", line 129, in _RunNinja
    subprocess.check_call(cmd)
  File "/root/webrtc/third_party/depot_tools/.cipd_bin/.cipd/pkgs/0/Gz9krHL6kKjbvGdxI5atUyCuwSXBMIhmVrK6FblTzSIC/3.8/lib/python3.8/subprocess.py", line 364, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['/root/webrtc/src/third_party/depot_tools/ninja', '-C', '/root/webrtc_build/aar/armeabi-v7a', 'sdk/android:libwebrtc', 'sdk/android:libjingle_peerconnection_so']' returned non-zero exit status 1.
make[2]: *** [Makefile:80: build] Error 1
make[2]: Leaving directory '/root/build/android'
make[1]: *** [Makefile:76: android.build-nofetch] Error 2
make[1]: Leaving directory '/root/build'
make: *** [Makefile:79: android] Error 2
make: *** [Makefile:80: android] Error 2
make: Leaving directory '/home/ubuntu/libwebrtc-bin/docker'`

Thanks in advance.

**Comment by crow-misia** [comment]
Because type is not same.
Try creating a patch and rebuilding.
